#
# RATE CONTROL MAKEFILE
#

# Configure
TARGET := rate_control.a
CUFILES := rate_control.cu

# Include Common Makefile
include ../../common.mk

# Headers for files
rate_control.cu.o: rate_control.cu rate_control.h

