#
# EBCOT MAKEFILE
#

# Configure
TARGET := ebcot.a
CFILES := t1.c
MODULES := mqc/mqc.a cxmod/gpu/cxmod.a

# Include Common Makefile
include ../../common.mk

# Headers for files
t1.c.o: t1.c t1.h mqc/mqc.h

