#
# T2 GPU MAKEFILE
#

# Configure
TARGET := t2_gpu.a
CXXFILES := t2_gpu.cpp

# Include Common Makefile
include ../../../common.mk

# Headers for files
t2_gpu.cpp.o: t2_gpu.cpp t2_gpu.h ../../j2k_encoder.h

