#
# OUTPUT COMPACTION MAKEFILE
#

# Configure
TARGET := compaction.a
CUFILES := compaction.cu

# Include Common Makefile
include ../../common.mk

# Headers for files
compaction.cu.o: compaction.cu compaction.h

