#
# DEMO ENCODER MAKEFILE
#

# Configure
TARGET := demo_enc.a
CXXFILES := demo_enc.cpp
MODULES := cuj2k/cuj2k.a

# Include Common Makefile
include common.mk

demo_enc.cpp.o: demo_enc.cpp demo_enc.h cuj2k/j2k_encoder_extended.h

