# SPDX-License-Identifier: BSD-3-Clause
# SPDX-FileCopyrightText: Copyright 2019-2026 CESNET, zájmové sdružení právnických osob

name: C/C++ CI

on:
  push:
    branches:
      - master
    tags:
      - v[0-9]+.*
    paths:
      - '.github/scripts/**'
      - '.github/workflows/ccpp.yml'
      - '.github/workflows/prepare.yml'
      - '.github/workflows/linux.yml'
      - '.github/workflows/macos.yml'
      - '.github/workflows/windows.yml'
      - '**.c'
      - '**.cpp'
      - '**.cu'
      - '**.h'
      - '**.hpp'
      - '**.m'
      - '**.mm'
      - 'autogen.sh'
      - 'configure.ac'
      - 'data/**'
      - 'Makefile.in'
  workflow_dispatch:

jobs:
  prepare:
    uses: ./.github/workflows/prepare.yml

  linux:
    needs: prepare
    uses: ./.github/workflows/linux.yml

  macos:
    needs: prepare
    uses: ./.github/workflows/macos.yml

  windows:
    needs: prepare
    uses: ./.github/workflows/windows.yml
