name: C/C++ CI

on:
  push:
    branches:
      - master
      - ci
      - ci-mac-ximea-working
    paths:
      - '.github/workflows/ccpp.yml'
      - '**.c'
      - '**.cpp'
      - '**.cu'
      - '**.h'
      - '**.hpp'
      - '**.m'
      - '**.mm'
      - 'autogen.sh'
      - 'configure.ac'
      - 'data/scripts/**.sh'
      - 'Makefile.in'

jobs:
  macOS:
    if: github.repository == 'CESNET/UltraGrid' || github.repository == 'MartinPulec/UltraGrid'
    name: run macOS
    runs-on: macos-latest
    env:
      AJA_DIRECTORY: "/var/tmp/ntv2sdk"
      UG_SKIP_NET_TESTS: 1
      CPATH: "/usr/local/include:/usr/local/opt/qt/include"
      LIBRARY_PATH: "/usr/local/lib:/usr/local/opt/qt/lib"
      PKG_CONFIG_PATH: "/usr/local/lib/pkgconfig:/usr/local/opt/qt/lib/pkgconfig"
      SDKROOT: "macosx10.14" # SDK 10.15 crashes Qt in High Sierra
      sdk_pass: ${{ secrets.sdk_pass }}
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: set-path
      run: echo "::add-path::/usr/local/opt/qt/bin"
    - name: bootstrap
      run: |
              curl -LO https://github.com/phracker/MacOSX-SDKs/releases/download/10.14-beta4/MacOSX10.14.sdk.tar.xz
              tar xJf MacOSX10.14.sdk.tar.xz
              mv MacOSX10.14.sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
              brew install autoconf automake cppunit dylibbundler libtool pkg-config
              brew install ffmpeg portaudio sdl2
              brew install ossp-uuid # for cineform
              ( cd cineform-sdk/ && cmake . && make CFHDCodecStatic )
    - name: Cache static Qt
      id: cache-qt-mac
      uses: actions/cache@v1
      with:
        path: /usr/local/opt/qt
        key: cache-qt-mac
    - name: Build static Qt
      if: steps.cache-qt-mac.outputs.cache-hit != 'true'
      run: |
              wget --no-verbose https://download.qt.io/archive/qt/5.13/5.13.2/single/qt-everywhere-src-5.13.2.tar.xz
              tar xJf qt-everywhere-src-5.13.2.tar.xz
              cd qt-everywhere-src-5.13.2
              ./configure -static -release -nomake examples -opensource -confirm-license -opengl -prefix /usr/local/opt/qt
              make -j 3 && sudo make install
    - name: Install XIMEA
      run: |
              if [ -z "$sdk_pass" ]; then exit 0; fi
              curl --netrc-file <(cat <<<"machine frakira.fi.muni.cz login sdk password $sdk_pass") https://frakira.fi.muni.cz/~xpulec/sdks/m3api.tar.xz -O
              sudo tar xJf m3api.tar.xz -C $(xcrun --show-sdk-path)/$SDKPATH/System/Library/Frameworks
    - name: Install AJA
      run: |
              if [ -z "$sdk_pass" ]; then exit 0; fi
              curl --netrc-file <(cat <<<"machine frakira.fi.muni.cz login sdk password $sdk_pass") https://frakira.fi.muni.cz/~xpulec/sdks/ntv2sdkmac.zip -O
              unzip ntv2sdkmac.zip -d /var/tmp
              mv /var/tmp/ntv2sdk* /var/tmp/ntv2sdk
              cd /var/tmp/ntv2sdk/ajalibraries/ajantv2/build
              xcodebuild -project ajantv2.xcodeproj
              sudo rm -f /usr/local/lib/libajantv2.dylib
              sudo cp ../../../bin/ajantv2.dylib /usr/local/lib/libajantv2.dylib
              sudo ln -fs /usr/local/lib/libajantv2.dylib /usr/local/lib/ajantv2.dylib
    - name: configure
      run: export CPATH LIBRARY_PATH PKG_CONFIG_PATH && ./autogen.sh --enable-qt --enable-static-qt
    - name: make
      run: make osx-gui-dmg
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
    - name: Upload build
      uses: actions/upload-artifact@v1
      with:
        name: UltraGrid CI macOS build
        path: UltraGrid.dmg


# vi: set expandtab sw=2:
